export enum ModalActionType {
    NO_ACTION = 'NOACTION',
    EMPTY = '',
    CONNECT_WALLET = 'connect_wallet',
    DEPOSIT_AND_BORROW = 'DEPOSIT_AND_BORROW',
    LEAVE_SMART_VAULT_ETH = 'LEAVESMARTVAULTETH',
    LEAVE_SMART_VAULT_BTC = 'LEAVESMARTVAULTBTC',
    DEPOSIT = 'DEPOSIT',
    WITHDRAW = 'WITHDRAW',
    BORROW = 'BORROW',
    PAYBACK = 'PAYBACK',
    STAKE_SMART_VAULT = 'STAKESMARTVAULT',
}