export enum ActionType {
    TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR',
    OPEN_SIDEBAR = 'OPEN_SIDEBAR',
    CLOSE_SIDEBAR = 'CLOSE_SIDEBAR',
    CHANGE_ACTIVE_SIDEBAR_ITEM = 'CHANGE_ACTIVE_SIDEBAR_ITEM',
    TOGGLE_LOADING = 'TOGGLE_LOADING',
}